const fs = require('fs');
const path = require('path');

// Read the HTML file
const html = fs.readFileSync(path.join(__dirname, 'src', 'index.html'), 'utf-8');

// Read the bookmarklet JS
const bookmarklet = fs.readFileSync(path.join(__dirname, 'src', 'bookmarklet.js'), 'utf-8');

// Generate worker.js with embedded HTML and bookmarklet
const workerCode = `// Auto-generated by build.js - do not edit directly
const HTML = ${JSON.stringify(html)};
const BOOKMARKLET_JS = ${JSON.stringify(bookmarklet)};

export default {
  async fetch(request) {
    const url = new URL(request.url);
    
    if (url.pathname === '/bookmarklet.js') {
      return new Response(BOOKMARKLET_JS, {
        headers: { 'Content-Type': 'application/javascript; charset=utf-8', 'Access-Control-Allow-Origin': '*' }
      });
    }
    
    return new Response(HTML, {
      headers: { 'Content-Type': 'text/html; charset=utf-8' }
    });
  }
};
`;

fs.writeFileSync(path.join(__dirname, 'src', 'worker.js'), workerCode);
console.log('Build complete: src/worker.js (' + workerCode.length + ' bytes)');
